### ISSUE TITLE
Can't test out the newly implemented OpenAL library

### ISSUE THREAD

**Issue by LePython** [noah1510/redhand#55]
Having implemented the new library, the obvious thing to do is to test it out, but since the testgame has no connection to the main redhand compiled code, it is not imported automatically. Should I just import the new audio.hpp + *.cpp script by hand?

**Comment by noah1510** [comment]
just run `./scripts/setup.sh``it will do everything for you.

**Comment by LePython** [comment]
Yeah... but how do I modify the testgame CMake file, so that it links the submodule properly?
![image](https://user-images.githubusercontent.com/12254191/90272271-72594800-de5d-11ea-8761-852ebfeeff00.png)

**Comment by LePython** [comment]
It might be a problem with how I linked the openal-soft submodule in the CMake file. Take a look at the recent commit e669c28707180f7febeaed829be791dd58ba7688

**Comment by noah1510** [comment]
the CMakeList.txt for the testgame needs the same changes because openal has to be linked for both projects.

cmake has a [function](https://cmake.org/cmake/help/v3.18/module/FindOpenAL.html) that is used to automatically find openal and get all the paths.
I will write a small fix to get everything to work correctly.

because of that opetion the submodule is not needed and a system installation of openal is required just like for opengl

The build is fixed in 2b94928

**Comment by LePython** [comment]
Thank you for fixing it! I have close to none experience with CMake so it would have taken me a few days to get it working

**Comment by noah1510** [comment]
I don't have that much experience with it either, I just google the parts I need most of the time someone had the same problem :sweat_smile:

**Comment by LePython** [comment]
The problem is that I hardly know the structure of the project. But that won't be the problem anymore since that was hopefully the last time implementing a new library
